# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: tonnyamaral
# "service" is the name of this project. This will also be added to your AWS resource names.
service: leve-serverless-app

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  # - serverless-plugin-typescript
  - serverless-offline

functions:
  listSchedules:
    handler: src/handler.listSchedules
    events:
      - http:
          path: schedules
          method: get

  createScheduling:
    handler: src/handler.createScheduling
    events:
      - http:
          path: schedulings
          method: post
